### ISSUE TITLE
eval-region

### ISSUE THREAD

**Issue by VanLaser** [xiongtx/eros#3]
Hi, this package is great! Would it be possible also to create a wrapper for `eval-region`? It would work wonders with my `evil-operator-eval` which is based on this function. I did try to wrap it into the `eros` overlay function, but unfortunately the result was always `nil` - so it seems I'm doing something wrong. Thanks! :)

**Comment by xiongtx** [comment]
By default, `eval-region` [does not return any output](http://git.savannah.gnu.org/cgit/emacs.git/tree/src/lread.c?h=emacs-26#n2123). You'd _think_ it'd return the value of the last form, but, alas, it doesn't.

The following implementation is _close_ to what you want (`|` is point, `█` is mark):

```emacs-lisp
(defun eros-eval-region (start end)
  (interactive "r")
  (eros--eval-overlay
   (string-trim
    (with-output-to-string
      (eval-region start end standard-output)))
      (max (point) (mark))))
   
|(+ 1 2)█ => "3"
```

However, since the output is always a string, the overlay is always a string, even if it should be a number etc.

And if you evaluate multiple forms in a region, the outputs are concatenated together:

```emacs-lisp
|(+ 1 2)
(+ 3 4)█ 
=> " 3

7"
```

You can play around w/ this until you get something satisfactory. Given the differences b/t `eval-region` and `eval-{last-sexp, defun}`, however, I won't be incorporating this into `eros`.
